[16.0][mig] pim: Migration to 16.0
OCA/odoo-pim pull request #165
Opened 2023-07-20 11:55 UTC by dsolanki-initos

2023-08-08 11:49 UTC, Camille0907 approved these changes
Migration LGTM

2023-08-09 13:19 UTC, simahawk requested changes
can you add test dependencies?

2023-08-09 13:19 UTC, simahawk commented on pim/data/ir_module_category_data.xml
> +        <field name="name">PIM</field>
I´d move this category and the base menu entry to a base_pim module so that it can be shared w/ all pim modules

2023-08-15 12:32 UTC, victorvermot commented
@sbejaoui Could you attend to simahawk's comments on this one as well ? Ty in advance

2023-11-23 12:11 UTC, simahawk commented
@dsolanki-initos ping

2024-01-19 06:54 UTC, hspl-priva approved these changes

2024-01-19 06:55 UTC, hspl-priva commented
LGTM @dsolanki-initos

2024-06-23 12:27 UTC, closed without merging

2026-03-23 09:42 UTC, cyrilmanuel commented
@fshah-initos  could you ping  @dsolanki-initos or reopen this pr please ?