[14.0][MIG] attribute set completeness xbo
OCA/odoo-pim pull request #86
Opened 2021-04-15 08:48 UTC by xavier-bouquiaux

@rousseldenis , @Cedric-Pigeon 

test ok

2021-04-21 06:47 UTC, rousseldenis requested changes
LGTM apart the changed computed field.

@xavier-bouquiaux

2021-04-21 06:47 UTC, rousseldenis commented on attribute_set_completeness/models/attribute_set_owner_mixin.py
> +        comodel_name="attribute.set.completeness", readonly=True
Why changing the field to a non computed one ?

The here under _compute_completion_rate method is still filling it...

2021-04-26 08:44 UTC, rousseldenis commented on attribute_set_completeness/__manifest__.py
> +    "website": "https://github.com/shopinvader/odoo-pim",
```suggestion
    "website": "https://github.com/OCA/odoo-pim",
```

2021-07-23 13:41 UTC, ivantodorovich requested changes

2021-07-23 13:41 UTC, ivantodorovich commented on attribute_set_completeness/__manifest__.py
> +    "author": "ACSONE SA/NV",
```suggestion
    "author": "ACSONE SA/NV, Odoo Community Association (OCA)",
```

2021-07-29 06:00 UTC, simahawk requested changes

2021-07-29 06:00 UTC, simahawk commented on attribute_set_completeness/__manifest__.py
> +# Copyright 2021 ACSONE SA/NV
2020 is correct

2021-07-29 06:00 UTC, simahawk commented on attribute_set_completeness/components/attribute_set_owner_event_listener.py
> +# Copyright 2021 ACSONE SA/NV (<http://acsone.eu>)
2020 everywhere unless you added new files

2021-07-29 06:00 UTC, simahawk commented on attribute_set_completeness/models/attribute_set_owner_mixin.py
> +        store=True,
store for?

2021-09-06 11:31 UTC, simahawk commented
replaced by https://github.com/OCA/odoo-pim/pull/98

2021-09-06 11:31 UTC, closed without merging